In [53]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너 (1차원 배열의 집합)
# 딥러닝이 학습할 때 사용하는 자료구조
# 미분 자동으로 계산
# 0차원 텐서 : 스칼라 - 단일 데이터 (숫자)
# 1치원 텐서(벡터) : 스칼라의 집합 (like 리스트)
# 2차원 텐서(행렬) : 행과 열로 이루어진 데이터, 표데이터, 흑백 이미지
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R G B)
# 고차원 텐서 : 동영상 : 이미지 개수 x 가로 픽셀 x 세로 픽셀 x 채널 정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효울적인 계산 : GPU 지원 -> 병렬연산에 유리
# 딥러닝 프레임 워크 : 텐서 플로, 파이토치

In [54]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [55]:
# 기본 연산
import torch

# 빈 텐서 생성
x = torch.empty(3,4)



In [ ]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.4006, 0.4182, 0.3997, 0.3845],
        [0.7069, 0.5253, 0.5304, 0.8317],
        [0.4574, 0.6263, 0.5375, 0.2509]])

In [57]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [58]:
# 1로 채워진 텐서
x = torch.ones(3,4,dtype=torch.long)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [59]:
import numpy as np
print(torch.tensor([3.5,3,2.1]))
print(np.array([3.5,3,2.1]))


tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [60]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn

In [61]:
# 텐서 연산
import torch 
x = torch.rand(3,4)
y = torch.rand(3,4)
x, y, x+y

(tensor([[0.8714, 0.5240, 0.4573, 0.9281],
         [0.0361, 0.3801, 0.3456, 0.1783],
         [0.7898, 0.7729, 0.0235, 0.8879]]),
 tensor([[0.7559, 0.1386, 0.9182, 0.5892],
         [0.2228, 0.5001, 0.2909, 0.2855],
         [0.5538, 0.6027, 0.3425, 0.5100]]),
 tensor([[1.6274, 0.6625, 1.3755, 1.5172],
         [0.2589, 0.8801, 0.6364, 0.4638],
         [1.3436, 1.3756, 0.3660, 1.3979]]))

In [62]:
torch.add(x,y)

tensor([[1.6274, 0.6625, 1.3755, 1.5172],
        [0.2589, 0.8801, 0.6364, 0.4638],
        [1.3436, 1.3756, 0.3660, 1.3979]])

In [63]:
# in-place  y = y + x  <->  y += x
y.add_(x)
y


tensor([[1.6274, 0.6625, 1.3755, 1.5172],
        [0.2589, 0.8801, 0.6364, 0.4638],
        [1.3436, 1.3756, 0.3660, 1.3979]])

In [ ]:
# 행렬 곱셈
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y), x@y # 파이썬 3.5  x@y

(tensor([[0.7577, 0.8318, 0.9351, 0.6669],
         [0.5150, 0.2510, 0.0879, 0.8151],
         [0.5199, 0.3962, 0.5945, 0.0257]]),
 tensor([[0.4296, 0.0363, 0.9907, 0.6686, 0.2381],
         [0.8760, 0.4964, 0.0810, 0.7191, 0.9450],
         [0.8421, 0.8107, 0.6139, 0.2449, 0.3297],
         [0.0146, 0.5649, 0.9229, 0.6522, 0.1574]]),
 tensor([[1.8512, 1.5753, 2.0075, 1.7687, 1.3798],
         [0.5269, 0.6750, 1.3367, 1.0779, 0.5171],
         [1.0713, 0.7120, 0.9358, 0.7948, 0.6982]]))

In [65]:
x = torch.tensor ()

TypeError: tensor() missing 1 required positional arguments: "data"

In [ ]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item())

(tensor(0.0924), 0.09239548444747925, torch.Tensor, float)

In [ ]:
# 텐서 크기 변경  reshape-> 명령어: view  / numpy 동일한 기능 = reshape
import torch
x = torch.rand(4,4)
y = x.view(16)    # y = x.view(-1) --> 괄호에 -1 넣으면 "자동계산"
x, y, x.shape, y.shape

(tensor([[0.9554, 0.6901, 0.2347, 0.3046],
         [0.4956, 0.0228, 0.1977, 0.2341],
         [0.0885, 0.8827, 0.5970, 0.1913],
         [0.0076, 0.9549, 0.6417, 0.2774]]),
 tensor([0.9554, 0.6901, 0.2347, 0.3046, 0.4956, 0.0228, 0.1977, 0.2341, 0.0885,
         0.8827, 0.5970, 0.1913, 0.0076, 0.9549, 0.6417, 0.2774]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [ ]:
# x = 4x4 행렬
# view = reshape (텐서 모양 변경)
# size = shape (텐서 모양 확인)
# 가독성 up  -  view, size 사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시
x.view(2,8) , x.size()   # = x.view(-1,8)  / 열이 8개면 행은 2개 여야만 하기에 -1로 자동계산 하도록 한다. 

tensor([[0.9554, 0.6901, 0.2347, 0.3046, 0.4956, 0.0228, 0.1977, 0.2341],
        [0.0885, 0.8827, 0.5970, 0.1913, 0.0076, 0.9549, 0.6417, 0.2774]])

In [ ]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
a.numpy()


array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
# 넘파이 -> 텐서
import torch
import numpy as np
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [ ]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda')  # "cuda = GPU"
    # 텐서들은 GPU에서 연산해야되기 때문에 GPU에서 생성
    x = torch.ones(5, device=device)   # GPU
    y = torch.ones(5)   # CPU
    y = y.to(device)   # CPU -> GPU로 이동
    z = x + y
    print(f'GPU 연산결과 : {z}')
    print(f'다시')


# 연산은 같은 디바이스 (CPU 아니면 GPU 중 하나)에서 해야한다.



False

In [ ]:
# 행렬 연산 공식
# 행렬의 곱
# (x, y)*(x1, y1) --> y와 x1 값이 같아야 함.
# 행렬곱의 결과 = (x, y1)

# 텐서: 딥러닝을 위해 만든 자료구조 / 내부에 GPU 연산에 특화된 구조 / 일반적인 모양은 넘파이와 동일
# 텐서는 GPU연산을 지원한다.


In [ ]:
# 자동 미분 (Autograd) : 매 계산과정마다 해당 계산과정의 미분값을 저장
# 파이토치 - required_grad = True 로 설정하면, '계산 그래프'라는 형태로 기록 (동영상 녹화화 비슷한 원리)
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다.

In [69]:
x = torch.ones(2,2,requires_grad=True)
x, x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [70]:
y = x + 2  # --> y도 계산 그래프에 추가가 되는 것
z = y*y*3
out = z.mean()
z, out


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [71]:
# 기울기 구하는 과정 : 역전파 --> 기울기 계산
# 최종결과 out에서부터 시작 -> 계산그래프를 거꾸로 거슬러 올라가며 미분의 연쇄법칙을 사용해서 미분값 계산
# out을 x에 대해 미분
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [ ]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2
# d-out/dxi = 


In [1]:
# 기울기 제어
# 역전파, torch.no_grad,  detach
# required_grad = True 연산 추적
import torch
x = torch.randn(3, requires_grad=True)
print(x)
# y는 x로부터 연산 기록을 물려받음
y = x*2
y.data.norm()  # 노름 (유클리드 노름) : 벡터의 크기를 측정하는 방법 (원점으로부터 벡터까지의 거리)
# 노름 -> 벡터 내 모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근 씌운 값
# y의 실제데이터의 크기를 확인해서 반복
i = 0
while y.data.norm() < 1000 :
    y = y*2
    i += 1
print(f'y:{y}')
print(f'반복횟수:{i}')

# 벡터에 대한 역전파(야코비안 행렬)
# 벡터를 벡터로 미분 --> 결과 : 야코비안 행렬
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 "야코비안-벡터" 곱을 계산해서 메모리를 절약

v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float) 
y.backward(v)
print(f'x.grad : {x.grad}')


tensor([-0.7985, -0.8802,  0.1383], requires_grad=True)
y:tensor([-817.6631, -901.3126,  141.5908], grad_fn=<MulBackward0>)
반복횟수:9
x.grad : tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


'''
스칼라 백워드  Scalar Backward : 역전파로 구하는 기울기가 하나일 때
out.backward()
최종점수가 숫자 하나 ex) 수학공부 1시간했을 때 최종점수에 몇 점의 영향을 줬는지
최종 목표가 하나 (스칼라) 이기 때문에 각 원인(각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backward : 기울기가 여러개 일 때
y.backward(v)
과목별 점수가 담긴 성적표(벡터) --> 공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함 / 국어성적? 영어성적?
가중치 또는 중요도를 알려주는 벡터 v = torch.tensor ([0.1,1.0,0.0001], dtype=torch.float)
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
'''

In [ ]:
# 각 학습을 진행하면서 도중에 모델의 성능 평가 필요  -->  기울기 계산 하면 안됌
with torch.no_grad():
    print (f'no_grad 내부 : {(x**2).requires_grad}')

# .detach() 계산그래프에서 텐서를 분리
print (f'detach ~~')
~~~

# 입력치 개수 = 가중치 개수  --> 행렬곱 계산


SyntaxError: invalid syntax (1164155076.py, line 7)